name: unit_tests

on:
  pull_request:
    branches:
      - main
    paths:
      - "*/**"
jobs:
  unit-tests:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm i
      - run: npm test